// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzGB_D6jS1MhmIeGop_Z5DarfAfbHKYrc',
    appId: '1:1012659471115:web:d18696c67a67301af1980e',
    messagingSenderId: '1012659471115',
    projectId: 'quick-campus-35b8e',
    authDomain: 'quick-campus-35b8e.firebaseapp.com',
    storageBucket: 'quick-campus-35b8e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6wejpz2dpy0RISNlLKT1v-VQwFsijjLM',
    appId: '1:1012659471115:android:603e9a40559a879af1980e',
    messagingSenderId: '1012659471115',
    projectId: 'quick-campus-35b8e',
    storageBucket: 'quick-campus-35b8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEU1FCi26ot5P7iaIMRHv_x0KLdx77RAQ',
    appId: '1:1012659471115:ios:0ba4bd89ba792a45f1980e',
    messagingSenderId: '1012659471115',
    projectId: 'quick-campus-35b8e',
    storageBucket: 'quick-campus-35b8e.firebasestorage.app',
    iosBundleId: 'com.example.quickcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEU1FCi26ot5P7iaIMRHv_x0KLdx77RAQ',
    appId: '1:1012659471115:ios:0ba4bd89ba792a45f1980e',
    messagingSenderId: '1012659471115',
    projectId: 'quick-campus-35b8e',
    storageBucket: 'quick-campus-35b8e.firebasestorage.app',
    iosBundleId: 'com.example.quickcampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzGB_D6jS1MhmIeGop_Z5DarfAfbHKYrc',
    appId: '1:1012659471115:web:a73faabe3232718ff1980e',
    messagingSenderId: '1012659471115',
    projectId: 'quick-campus-35b8e',
    authDomain: 'quick-campus-35b8e.firebaseapp.com',
    storageBucket: 'quick-campus-35b8e.firebasestorage.app',
  );
}
